#! /usr/bin/env python
# small script to create colored 2D heatmaps from an output file
# generated by heat2d.c
import numpy as np
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
import sys

colormap='hot_r'
if len(sys.argv) != 2:
	print("Usage: heatmap <inputfile>")
	sys.exit(-1)

fname = sys.argv[1]
f = open(fname)
outfile = fname.split('.')[0] + ".png"
M = int(f.readline().strip())
N = int(f.readline().strip())
data = []
for l in f.readlines():
	data.append(map(lambda x: float(x),l.strip().split()))

npA = np.array(data)
# range the entries to be 0 .. 100
# offset
minv = npA.min()
npA -= minv
# scale
maxv = npA.max()
npA *= (100/maxv)
# Create plot
fig = plt.figure()
plt.imshow(npA,cmap=colormap)
plt.show()
plt.savefig(outfile)
